services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MYSQL_URL: mysql://root:rootpassword@mysql:3306/projects_db
    networks:
      - frontend
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: http://localhost:3000
      CHOKIDAR_USEPOLLING: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    ports:
      - "3001:3001"
    networks:
      - frontend

networks:
  frontend:
  backend:

volumes:
  mysql_data:
